name: hanzi_app
description: "宝宝识字 - 帮助学前儿童学习汉字的趣味应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cs_framework:
    git:
      url: https://github.com/bryanpeng-777/cs_framework.git
      ref: main
  cs_ui:
    git:
      url: https://github.com/bryanpeng-777/cs_ui.git
      ref: main
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_animate: ^4.5.2
  audioplayers: ^6.1.0
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/default_configs.json
